<div id="alert-area"></div>
<form id="suggestForm" name="form1" method="post" onsubmit="suggestPlace(); return false;"
			class="well hekaya-border">
			<fieldset>
                            <label><?=  Application_Service_Translate::_('from')?></label> <select name="from" id="from" size="1.1">
			<option value=0><?=  Application_Service_Translate::_('choose')?></option>
                        <option value="أخرى">أخرى</option>
                        
		</select> 
                            <label id="newPLabel">أخرى</label> <label></label> <input type="text"
			name="newParent" id="newParent"
			title="حى" />
                              <label id="newCLabel">أسم  المنطقة</label> <label></label> <input type="text"
			name="name" id="name"
			title="منطقة" />
                              
                              <br />
                              <input type="submit" name="button" id="button" value="<?=  Application_Service_Translate::_('share')?>" class="add-hekaya-btn" />
                            </fieldset>
		</form>

			<script type="text/javascript">
           function suggestPlace(){
           if($("#from").val() == 0){
            $("#alert-area").append($("<div id=\"error-alert\" class=\"alert alert-error\"><a class=\"close\" data-dismiss=\"alert\">×</a> <strong>أختار منطقة</strong></div> "));
            $("#error-alert").delay(2000).fadeOut("slow", function () { $(this).remove(); });
            return false;
        }else{
            if($("#name").val() == ''){
                $("#alert-area").append($("<div id=\"error-alert\" class=\"alert alert-error\"><a class=\"close\" data-dismiss=\"alert\">×</a> <strong>أختار مكان</strong></div> "));
                $("#error-alert").delay(2000).fadeOut("slow", function () { $(this).remove(); });
                return false;                
            }
        }
           $.ajax({
                url: "<?= $this->url(array('controller'=>'suggest','action'=>'post'),'default',true) ?>",
                dataType: "json", 
                data: $('#suggestForm').serialize(),
                beforeSend:function(){ //disable button and field
                   $('#from').attr("disabled","disabled");
                   $('#name').attr("disabled","disabled");
                },
                complete: function(){//enable them back
                    $('#name').attr("value","");
                    $('#from').removeAttr("disabled");
                    $('#name').removeAttr("disabled");
                },
                success: function(data) {
                    if(data){
                        successMsg("<?=  Application_Service_Translate::_('suggest_place_success_msg')?>")
                    }
                }
             });
        }
                            
$(document).ready(function(){
    
    $("#error-alert").hide();
  		
    loadCascadingCombo("from","fromHS");
//    loadCascadingCombo("to","toHS");
    $("#newParent").hide();
    $("#newPLabel").hide();
    
    //أخرى
    $('#form1').submit(function() {
        
        
    });
    
    $("#from").change(function(){
        if($("#from").val() == "أخرى"){
            $("#name").hide();
            $("#newCLabel").hide();
            $("#newParent").show();
            $("#newPLabel").show();                
        }else{
            $("#name").show();
            $("#newCLabel").show();
            $("#newParent").hide();
            $("#newPLabel").hide();                                
        }
    });
    
    function loadCascadingCombo(parentId,childId){
        $.ajax({
            url: "<?=$this->url(array('controller'=>'ajax','action'=>'gettoplevelareas'),'default',true)?>",
            cache: false,
            dataType: "json",
            success: function(data){
                $.each(data, function(i, item) {
                    $("#"+parentId).append($('<option/>').val(data[i].id).text(data[i].name));
                });
			  
            },
            error: function(e, xhr){
                alert("error");
            }
        });
      }
});

</script>
