<script>
    
    function OnFocusInput2(textarea) {

		$('textarea.expand').animate({
			height : "100em"
		}, 2);

		parseCharCounts();
	}0
	function OnBlurInput2(textarea) {
		if ($("textarea.expand").val() == "")
			$("textarea.expand").animate({
				height : "20em"
			}, 2);

	}

</script>

<form id="form2" name="form2" method="post" action="<?=$this->url(array('controller'=>'hakawy','action'=>'submit'),'default',true)?>" class="well">
<fieldset>
<textarea class="expand" 
id="taxiTalksInput" name="taxiTalksInput" maxlength="500"  onfocus="OnFocusInput2(this)" onblur="OnBlurInput2(this)" placeholder="قول للناس حدوتك"></textarea>
		<input type="submit" name="button" id="button" value="<?=  Application_Service_Translate::_('share')?>" class="btn btn-large" />
	 </fieldset>
</form>
<script type="text/javascript" src="/js/charcount.js"></script>

<!-- YAMLI CODE START -->
<script type="text/javascript" src="http://api.yamli.com/js/yamli_api.js"></script>

		<script type="text/javascript">
  if (typeof(Yamli) == "object" && Yamli.init( { uiLanguage: "ar" , startMode: "offOrUserDefault" } ))
  {
    Yamli.yamlify( "taxiTalksInput", { settingsPlacement: "inside" } );
  }
</script>