<form id="form2" name="form2" method="post" action="<?=$this->url(array('controller'=>'hakawy','action'=>'submit'),'default',true)?>" class="well">
<fieldset>
<textarea class="expand" 
id="taxiTalksInput" name="taxiTalksInput" maxlength="500"  onfocus="OnFocusInput (this)" onblur="OnBlurInput (this)" placeholder="قول للناس حدوتك"></textarea>
		<input type="submit" name="button" id="button" value="انشر" class="btn btn-large" />
	 </fieldset>
</form>
<script type="text/javascript" src="/js/charcount.js"></script>
<!-- YAMLI CODE START -->
<script type="text/javascript" src="http://api.yamli.com/js/yamli_api.js"></script>

		<script type="text/javascript">
  if (typeof(Yamli) == "object" && Yamli.init( { uiLanguage: "ar" , startMode: "offOrUserDefault" } ))
  {
    Yamli.yamlify( "taxiTalksInput", { settingsPlacement: "inside" } );
  }
</script>