<form id="form2" name="form2" method="post" action="<?=$this->url(array('controller'=>'submit','action'=>'post'),'default',true)?>"
	class="well">
	<fieldset>
		 <label><?=  Application_Service_Translate::_('paid_fare')?></label> <label></label> <input type="text"
			name="fare" id="fare" class="form-poshytip"
			title="$ $ $" />
		<label><?=  Application_Service_Translate::_('from')?></label> <select size="1.1" name="from" id="from">
			<option value=0><?=  Application_Service_Translate::_('choose')?></option>
                </select > <select  size="1.1" name="fromHS" id="fromHS">
			<option value=0><?=  Application_Service_Translate::_('choose')?></option>
		</select>
		<label><?=  Application_Service_Translate::_('address')?></label> <label></label> <input type="text"
			name="fromAddr" id="fromAddr" class="form-poshytip"
			title="Address" /> 
		<label><?=  Application_Service_Translate::_('to')?></label> <select name="to" size="1.1" id="to">
			<option value=0><?=  Application_Service_Translate::_('choose')?></option>
                </select> <select size="1.1" name="toHS" id="toHS">
			<option value=0><?=  Application_Service_Translate::_('choose')?></option>
		</select>
			<label><?=  Application_Service_Translate::_('address')?></label> <label></label> <input type="text"
			name="toAddr" id="toAddr" class="form-poshytip"
			title="Address" />
		
		<div class="control-group">
			<label class="control-label"><?=  Application_Service_Translate::_('taxi_type')?> </label>
			<div class="controls">
				<img class="imgRadio" src="/img/blackTaxis.jpg" data-value="1" />
						<img class="imgRadio" src="/img/whiteTaxis.jpg" data-value="2" />
						<img class="imgRadio" src="/img/yellowTaxis.jpg" data-value="3" />
						<img class="imgRadio" src="/img/londonTaxis.jpg" data-value="4" />
						<input type="hidden" id="imgRadio-input" name="imgRadio-input" />
			</div>
		</div>
		<div class="control-group">
			<label class="control-label"><!--<fmt:message key="form.search.type"/>--> <?=  Application_Service_Translate::_('traffic')?> </label>
			<div class="controls">
				<label class="radio"> <input type="radio" name="traffic"
					value="2" id="White" /> <?=  Application_Service_Translate::_('traffic_crowded_1')?>
				</label>
				 <label class="radio"> <input type="radio"
					name="traffic" value="3" id="Yellow" /> <?=  Application_Service_Translate::_('traffic_crowded_2')?>
				</label>
				 <label class="radio"> <input type="radio"
					name="traffic" value="1" id="Black" /> <?=  Application_Service_Translate::_('traffic_crowded_3')?>
				</label>
			</div>
		</div>
			<label><?=  Application_Service_Translate::_('comment')?></label> 
			<label></label> 
			<textarea type="text" name="comment" id="comment" class="form-poshytip" title="Comments" rows="4" cols="400"></textarea><br />
		
		<input type="submit" name="button" id="button" value="<?=  Application_Service_Translate::_('share')?>" class="btn btn-large" />
	</fieldset>
</form>

		<script type="text/javascript">
$(document).ready(function(){
  		
    loadCascadingCombo("from","fromHS");
    loadCascadingCombo("to","toHS");
    
    function loadCascadingCombo(parentId,childId){
        $.ajax({
            url: "<?=$this->url(array('controller'=>'ajax','action'=>'gettoplevelareas'),'default',true)?>",
            cache: false,
            dataType: "json",
            success: function(data){
                $.each(data, function(i, item) {
                    $("#"+parentId).append($('<option/>').val(data[i].id).text(data[i].name));
                });
			  
            },
            error: function(e, xhr){
                alert("error");
            }
        });
  		  		
	$("#"+parentId).change(function(){
                $.ajax({
                    url: "<?=$this->url(array('controller'=>'ajax','action'=>'getareasunder'),'default',true)?>",
                    dataType: "json", 
                    data: {id : $(this).val()},
                    success: function(data) {
                        $("#"+childId).empty();
                        $.each(data, function(i, item) {
                            $("#"+childId).append($('<option/>').val(data[i].id).text(data[i].name));
                        });
                        $("#"+childId).trigger("change");
                    }});


        });
    }
	

	
});

</script>
