<div id="alert-area"></div>
<form id="form2" name="form2" method="post" action="<?=$this->url(array('controller'=>'submit','action'=>'post'),'default',true)?>"
	class="well hekaya-border-search">
	<fieldset>
		 <label><?=  Application_Service_Translate::_('paid_fare')?></label> <label></label> <input type="text"
			name="fare" id="fare"
			title="$ $ $" />
                 <br></br>
		<label><?=  Application_Service_Translate::_('from')?></label> <select size="1.1" name="from" id="from">
			<option value=-1><?=  Application_Service_Translate::_('choose')?></option>
                </select > <select  size="1.1" name="fromHS" id="fromHS">
			<option value=-1><?=  Application_Service_Translate::_('choose')?></option>
		</select>
                &nbsp;
                           <a style="font-size: smaller;" href="<?=$this->url(array('controller'=>'suggest','action'=>'index'),'default',true)?>"><?=  Application_Service_Translate::_('suggest_link')?></a>

                                            <br></br>
		<label><?=  Application_Service_Translate::_('address')?></label> <label></label> <input type="text"
			name="fromAddr" id="fromAddr"
			title="Address" /> 
                                 <br></br>
		<label><?=  Application_Service_Translate::_('to')?></label> <select name="to" size="1.1" id="to">
			<option value=-1><?=  Application_Service_Translate::_('choose')?></option>
                </select> <select size="1.1" name="toHS" id="toHS">
			<option value=-1><?=  Application_Service_Translate::_('choose')?></option>
		</select>
                &nbsp;
                
                           <a style="font-size: smaller;" href="<?=$this->url(array('controller'=>'suggest','action'=>'index'),'default',true)?>"><?=  Application_Service_Translate::_('suggest_link')?></a>
		                 <br></br>	
			<label><?=  Application_Service_Translate::_('address')?></label> <label></label> <input type="text"
			name="toAddr" id="toAddr"
			title="Address" />
                        <br>
                                                <br>
		<div class="control-group">
			<label class="control-label"><?=  Application_Service_Translate::_('taxi_type')?> </label>
			<div class="controls">
                            <img class="imgRadio" src="/img/blackTaxi.png" data-value="1"/>
                            <img class="imgRadio" src="/img/whiteTaxi.png" data-value="2"/>
                            <img class="imgRadio" src="/img/yellowTaxi.png" data-value="3"/>
                            <img class="imgRadio" src="/img/londonTaxi.png" data-value="4"/>
                            <input type="hidden" id="imgRadio-input" name="imgRadio-input" />
			</div>
		</div>
                        <br>
		<div class="control-group">
			<label class="control-label"><!--<fmt:message key="form.search.type"/>--> <?=  Application_Service_Translate::_('traffic')?> </label>
			<div class="controls">
				<label class="radio"> <input type="radio" name="traffic"
					value="3" id="White" /> <?=  Application_Service_Translate::_('traffic_crowded_1')?>
				</label>
				 <label class="radio"> <input type="radio"
					name="traffic" value="2" id="Yellow" /> <?=  Application_Service_Translate::_('traffic_crowded_2')?>
				</label>
				 <label class="radio"> <input type="radio"
					name="traffic" value="1" id="Black" /> <?=  Application_Service_Translate::_('traffic_crowded_3')?>
				</label>
			</div>
		</div>
<br>
			<label><?=  Application_Service_Translate::_('comment')?></label> 
                        
                        
                        <textarea  onfocus="parseCharCounts()" class="leave-comments" type="text" name="comment" id="comment" title="" maxlength="500"></textarea><br />
		
		<input type="submit" name="button" id="button" value="<?=  Application_Service_Translate::_('share')?>" class="add-hekaya-btn" />
	</fieldset>
</form>
<script type="text/javascript" src="/js/charcount.js"></script>

		<script type="text/javascript">
                    
                    
$(document).ready(function(){
  		
    loadCascadingCombo("from","fromHS");
    loadCascadingCombo("to","toHS");
    
    function loadCascadingCombo(parentId,childId){
        $.ajax({
            url: "<?=$this->url(array('controller'=>'ajax','action'=>'gettoplevelareas'),'default',true)?>",
            cache: false,
            dataType: "json",
            success: function(data){
                $.each(data, function(i, item) {
                    $("#"+parentId).append($('<option/>').val(data[i].id).text(data[i].name));
                });
			  
            },
            error: function(e, xhr){
                console.log("ajax error");
            }
        });
  		  		
	$("#"+parentId).change(function(){
                $.ajax({
                    url: "<?=$this->url(array('controller'=>'ajax','action'=>'getareasunder'),'default',true)?>",
                    dataType: "json", 
                    data: {id : $(this).val()},
                    success: function(data) {
                        $("#"+childId).empty();
                        $.each(data, function(i, item) {
                            $("#"+childId).append($('<option/>').val(data[i].id).text(data[i].name));
                        });
                        $("#"+childId).trigger("change");
                    }});
        });
    }
	
    $('#form2').submit(function() { 
        if($("#from").val() == -1){
            $("#alert-area").append($("<div id=\"error-alert\" class=\"alert alert-error\"><a class=\"close\" data-dismiss=\"alert\">×</a> <strong>أختار منين</strong></div> "));
            $("#error-alert").delay(2000).fadeOut("slow", function () { $(this).remove(); });
            $('html, body').animate({scrollTop:0}, 'slow');
            return false;
        }else if($("#fromHS").val() == -1){
            $("#alert-area").append($("<div id=\"error-alert\" class=\"alert alert-error\"><a class=\"close\" data-dismiss=\"alert\">×</a> <strong>أختار منين</strong></div> "));
            $("#error-alert").delay(2000).fadeOut("slow", function () { $(this).remove(); });
            $('html, body').animate({scrollTop:0}, 'slow');
            return false;
        }else if($("#to").val() == -1){
            $("#alert-area").append($("<div id=\"error-alert\" class=\"alert alert-error\"><a class=\"close\" data-dismiss=\"alert\">×</a> <strong>أختار لفين</strong></div> "));
            $("#error-alert").delay(2000).fadeOut("slow", function () { $(this).remove(); });
            $('html, body').animate({scrollTop:0}, 'slow');
            return false;
        }else if($("#toHS").val() == -1){
            $("#alert-area").append($("<div id=\"error-alert\" class=\"alert alert-error\"><a class=\"close\" data-dismiss=\"alert\">×</a> <strong>أختار لفين</strong></div> "));
            $("#error-alert").delay(2000).fadeOut("slow", function () { $(this).remove(); });
            $('html, body').animate({scrollTop:0}, 'slow');
            return false;
        }else if($("#imgRadio-input").val() == ''){
            $("#alert-area").append($("<div id=\"error-alert\" class=\"alert alert-error\"><a class=\"close\" data-dismiss=\"alert\">×</a> <strong>أختار لون التاكسى</strong></div> "));
            $("#error-alert").delay(2000).fadeOut("slow", function () { $(this).remove(); });
            $('html, body').animate({scrollTop:0}, 'slow');
            return false;
        }else if($("#toHS").val() == $("#fromHS").val()){
            $("#alert-area").append($("<div id=\"error-alert\" class=\"alert alert-error\"><a class=\"close\" data-dismiss=\"alert\">×</a> <strong>مينفعش تختار نفس المنطقة</strong></div> "));
            $("#error-alert").delay(2000).fadeOut("slow", function () { $(this).remove(); });
            $('html, body').animate({scrollTop:0}, 'slow');
            return false;
        }else if($("#fare").val() == ''){
            $("#alert-area").append($("<div id=\"error-alert\" class=\"alert alert-error\"><a class=\"close\" data-dismiss=\"alert\">×</a> <strong>قولنا دفعت كام</strong></div> "));
            $("#error-alert").delay(2000).fadeOut("slow", function () { $(this).remove(); });
            $('html, body').animate({scrollTop:0}, 'slow');
            return false;
        }else if($("#traffic").val() == ''){
            $("#alert-area").append($("<div id=\"error-alert\" class=\"alert alert-error\"><a class=\"close\" data-dismiss=\"alert\">×</a> <strong>إيه نظام الطريق؟</strong></div> "));
            $("#error-alert").delay(2000).fadeOut("slow", function () { $(this).remove(); });
            $("#alert-area").focus();
            $('html, body').animate({scrollTop:0}, 'slow');
            return false;
        }
    });	
});

</script>
