<script type="text/javascript">
    var nickSet = <?php echo $this->nickset ?>;
    $(document).ready(function(){
        //on enter submit the form
        $('#comment').keypress(function(e){
            if(e.which == 13){
                e.preventDefault();
                addComment();
            }
        });
        
        //get the comments on hekaya
        $.ajax({
            url: "<?= $this->url(array('controller' => 'comments', 'action' => 'index','id'=>$this->id), 'default', true) ?>",
            success: function(data) {
                $(".comments").append(data.html);
            }
        });
    });
    function addComment(){
        
        if(!nickSet){//no nickname
            addNick();
        }
        
        $.ajax({
            url: "<?= $this->url(array('controller' => 'comments', 'action' => 'post'), 'default', true) ?>",
            dataType: "json", 
            data: $('#commentForm').serialize(),
            beforeSend:function(){ //disable button and field
                $('#comment').attr("disabled","disabled");
            },
            complete: function(){//enable them back
                $('#comment').attr("value","");
                $('#comment').removeAttr("disabled");
            },
            success: function(data) {
                $(".comments").append(data.html);
                var currNum = $('#no_comments_<?=$this->id?>').html();
                $('#no_comments_<?=$this->id?>').html(++currNum);
            }
        });
    }
</script>
<div class="comments">
    
</div>
<form id="commentForm">
    <input type="hidden" name="id" value="<?=$this->id?>"/>
    <input type="hidden" name="sock_id" id="sock_id"/>
    <textarea class="comment-expand" id="comment" name="comment" maxlength="300" placeholder="<?= Application_Service_Translate::_('add_your_comment') ?>"></textarea>
</form>