<script type="text/javascript">
    var nickSet = <?php echo $this->nickset ?>;
    var getCommentsUrl = "<?= $this->url(array('controller' => 'comments', 'action' => 'index','id'=>$this->id), 'default', true) ?>";
    var sendCommentUrl = "<?= $this->url(array('controller' => 'comments', 'action' => 'post'), 'default', true) ?>";
    var id = "<?=$this->id?>";
</script>
<?php
echo $this->headScript()->appendFile('/js/comments.js','text/javascript',array('var1'=>'tada'));
?>
<div id="alert-area"></div>
<div class="comments">
    
</div>
<form id="commentForm">
    <input type="hidden" name="id" value="<?=$this->id?>"/>
    <input type="hidden" name="sock_id" id="sock_id"/>
    <textarea class="comment-expand" id="comment" name="comment" maxlength="300" placeholder="<?= Application_Service_Translate::_('add_your_comment') ?>"></textarea>
</form>