<?php
    $hekayaUrl = $this->serverUrl().$this->url(array('controller'=>'hakawy','action'=>'get','id'=>$this->hekaya['id']),'default',true);
?>
<script>
        !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];
        if(!d.getElementById(id))
            {
                js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";
                fjs.parentNode.insertBefore(js,fjs);
            }
        }(document,"script","twitter-wjs");
</script>

 <div class="record">
   <img src="/img/dot.png" class="record-bg"/>
   <p class="nickname-text"><?=  Application_Service_Translate::_('hadoota')?> <?=$this->hekaya['nickname']?> : </p>
   
   <p>
       <?= Application_Service_TextFormatting::htmlNlEncoding2Br($this->hekaya['text'])?>
   <div >
   
       <a class="popup fb-t-share record-controls" href="http://www.facebook.com/sharer.php?u=<?=$hekayaUrl?>"><img src="/img/social-icons/circular/facebook_32.png" height="20px" width="20px"></img></a>
       <a class="popup fb-t-share record-controls" href="https://twitter.com/share?hashtags=ElOgra&url=<?=$hekayaUrl?>&text=<?=  substr($this->hekaya['text'], 0, 100)?> ..." ><img src="/img/social-icons/circular/twitter_32.png" height="20px" width="20px"></img></a>
   

       <a class="delete record-controls" href="#" id="<?=$this->hekaya['id']?>" data-id="<?=$this->hekaya['id']?>" data-type="<?=Application_Model_DBConstants::REPORT_TYPE_HAKAWY?>" onclick="javascript:report(this)"><?=  Application_Service_Translate::_('spam')?></a>
       
       <a class="likes record-controls" href="#!" id="<?=$this->hekaya['id']?>" data-id="<?=$this->hekaya['id']?>" data-type="<?=Application_Model_DBConstants::HAKAWY_LIKE?>" onclick="javascript:like(this)"><?=  Application_Service_Translate::_('like')?></a>
       (<span id="<?='no_likes_'.$this->hekaya['id']?>"><?=$this->hekaya['likes']?></span>) 

   </div>
   </p>    
</div>