<!DOCTYPE html>
<html lang="en">
	<head>
            <script type="text/javascript">
var updateLayout = function() {
  if (window.innerWidth != currentWidth) {
    currentWidth = window.innerWidth;
    var orient = (currentWidth == 320) ? "profile" : "landscape";
    document.body.setAttribute("orient", orient);
    window.scrollTo(0, 1);
  }
};

iPhone.DomLoad(updateLayout);
setInterval(updateLayout, 400);
</script>
		<meta charset="utf-8">              
                <meta name="viewport" content="width=device-width" >
		<title>الأجرة  | حكاوي المشاوير </title>
		<meta charset="utf-8">
                <title><?=  Application_Service_Translate::_('site_title')?> </title>
		
		<link rel='icon' href='img/favicon.ico'/>
		 <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.js"></script>
    <script type="text/javascript" src="/js/jquery-ui.js"></script>
		
		<!-- CSS -->
		<link rel="stylesheet" href="/css/style.css" type="text/css" media="screen" />
		<link rel="stylesheet" href="/css/social-icons.css" type="text/css" media="screen" />
	
		<!-- THEME -->
		<link rel="stylesheet" href="/skins/paper-brown/style.css" type="text/css" media="screen" />
		
		<!-- JS -->
		<script type="text/javascript" src="/js/easing.js"></script>
		<script type="text/javascript" src="/js/extras.js"></script>
                
                
                
		<script type="text/javascript" src="/js/jquery.scrollTo-1.4.2-min.js"></script>
		<script type="text/javascript" src="/js/quicksand.js"></script>
		<script type="text/javascript" src="/js/custom.js"></script>
		<!--[if IE]>
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<!-- ENDS JS -->
		
		<!--[if IE 6]>
			<script type="text/javascript" src="js/DD_belatedPNG.js"></script>
			<script>
	      		/* EXAMPLE */
	      		//DD_belatedPNG.fix('*');
	    	</script>
		<![endif]-->
		
		<!-- superfish -->
		<link rel="stylesheet" media="screen" href="/css/superfish.css" /> 
		<link rel="stylesheet" media="screen" href="/css/superfish-left.css" /> 
		<script type="text/javascript" src="/js/superfish-1.4.8/js/hoverIntent.js"></script>
		<script type="text/javascript" src="/js/superfish-1.4.8/js/superfish.js"></script>
		<!-- ENDS superfish -->
		
<!--		 poshytip 
-->		<link rel="stylesheet" href="/js/poshytip-1.0/src/tip-twitter/tip-twitter.css" type="text/css" />
		<link rel="stylesheet" href="/js/poshytip-1.0/src/tip-yellowsimple/tip-yellowsimple.css" type="text/css" />
		<script type="text/javascript" src="/js/poshytip-1.0/src/jquery.poshytip.min.js"></script><!--
		 ENDS poshytip -->
		
<!--		 Tweet 
		<link rel="stylesheet" href="/css/jquery.tweet.css" media="all"  type="text/css"/> 
		<script src="/js/tweet/jquery.tweet.js" type="text/javascript"></script> 
		 ENDS Tweet -->
		
		<!-- Fancybox -->
<!--		<link rel="stylesheet" href="/js/jquery.fancybox-1.3.4/fancybox/jquery.fancybox-1.3.4.css" type="text/css" media="screen" />
		<script type="text/javascript" src="/js/jquery.fancybox-1.3.4/fancybox/jquery.fancybox-1.3.4.pack.js"></script>-->
		<!-- ENDS Fancybox -->
		
		<!-- jflickrfeed -->
<!--		<link href="/css/jflickrfeed.css" rel="stylesheet" type="text/css" media="screen" /> 
		<script src="/js/jflickrfeed/jflickrfeed.js"></script>
		
		<link href="/js/jflickrfeed/colorbox/colorbox.css" rel="stylesheet" type="text/css" media="screen" /> 
		<script src="/js/jflickrfeed/colorbox/jquery.colorbox.js"></script>-->
		<!-- ENDS jflickrfeed -->
		
		<!-- prettyPhoto -->
<!--		<script type="text/javascript" src="/js/prettyPhoto/js/jquery.prettyPhoto.js"></script>
		<link rel="stylesheet" href="/js/prettyPhoto/css/prettyPhoto.css" type="text/css" media="screen" />-->
		<!-- ENDS prettyPhoto -->
		
		<!-- GOOGLE FONTS -->
<!--		<link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz' rel='stylesheet' type='text/css'>-->
				
		<!-- Nivo slider -->
<!--		<link rel="stylesheet" href="/css/nivo-slider.css" type="text/css" media="screen" />
		<script src="/js/nivo-slider/jquery.nivo.slider.js" type="text/javascript"></script>-->
		<!-- ENDS Nivo slider -->
		
		<!-- tabs -->
		<link rel="stylesheet" href="/css/tabs.css" type="text/css" media="screen" />
		<script type="text/javascript" src="/js/tabs.js"></script>
  		<!-- ENDS tabs -->
  		
		     <!-- bootstrap -->
     <link rel="stylesheet" href="/css/bootstrap/bootstrap-rtl.min.css" type="text/css"/>
     <script type="text/javascript" src="/js/bootstrap/bootstrap.min.js"></script>
     <link href="/css/bootstrap/extra.css" rel="stylesheet" type="text/css"/>
     <!-- bootstrap -->
     
     
  		

		<!--[if IE 7]>
			<link rel="stylesheet" type="text/css" media="screen" href="css/ie7-hacks.css" />
		<![endif]-->
		<!--[if IE 8]>
			<link rel="stylesheet" type="text/css" media="screen" href="css/ie8-hacks.css" />
		<![endif]-->
		<!-- ENDS CSS -->	
	<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-32426890-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>		
	</head>
	<body dir="rtl">
	
	<!-- WRAPPER -->
	<div id="wrapper">
	
		<!-- SIDEBAR -->
		<div id="sidebar">
			<!-- logo -->
                        <a href="<?=$this->url(array('controller'=>'index','action'=>'index'),'default',true)?>"><img src="/img/logo.png" alt="Left template" id="logo" /></a>
						
			<!-- Navigation class="current-menu-item" -->
		  <ul id="nav" class="sf-menu sf-vertical">
<li><a href="<?=$this->url(array('controller'=>'hakawy','action'=>'index'),'default',true)?>"><?=  Application_Service_Translate::_('taxi_talks_link')?></a></li>
<li><a href="<?=$this->url(array('controller'=>'search','action'=>'index'),'default',true)?>"><?=  Application_Service_Translate::_('search_link')?></a></li>				
<li><a href="<?=$this->url(array('controller'=>'submit','action'=>'index'),'default',true)?>"><?=  Application_Service_Translate::_('submit_link')?></a></li>
<li><a href="<?=$this->url(array('controller'=>'fares','action'=>'index'),'default',true)?>"><?=  Application_Service_Translate::_('fares_link')?></a></li>
<li><a href="<?=$this->url(array('controller'=>'suggest','action'=>'index'),'default',true)?>"><?=  Application_Service_Translate::_('suggest_link')?></a></li>
			<!-- Navigation -->	
					
			<!-- categories --><!-- categories -->	
			<!-- latest tweets --><!-- ENDS latest tweets -->
			
                        </ul>
			<!-- Social -->
			<ul class="social">
                                                   <br>
                                                      <br>
                                                   <br>                                                    
                                                   
                                                   <br>                                                    
                                                   <br>
                                                   <br>                                                    
                                                   <br>
                                                   <br>
                                                   <br>
                       </ul>
                               <p class="social" style="font-size:larger;"><?=  Application_Service_Translate::_('follow')?></p>
                           
                           <ul class="social">
                               <a href="http://www.facebook.com/" class="facebook" title="<?=  Application_Service_Translate::_('facebook')?>"></a>
                               <a href="http://www.twitter.com/" class="twitter" title="<?=  Application_Service_Translate::_('twitter')?>"></a>
                               
                       </ul>
                        <!-- ENDS Social -->

		</div>
		<!-- ENDS SIDEBAR -->
		
		<!-- MAIN -->
	  <div id="main">
		
			<!-- CONTENT -->
			<div id="content">
				<!-- PAGE CONTENT -->
				<div id="page-content">
					
					<!-- feature blocks -->
				  <h1 class="header-line">الأجرة ...حكاوى المشاوير</h1>
					<!-- ENDS feature blocks -->
										
					
				<?=$this->layout()->content?>
					
					
					
					
				</div>
				<!-- ENDS PAGE-CONTENT -->
			
		</div>
			<!-- ENDS CONTENT -->
			
	  </div>

                <!-- ENDS MAIN -->
	
        
        </div>
	<!-- ENDS WRAPPER -->

	<!-- FOOTER -->

		<!-- ENDS FOOTER-WRAPPER -->
	<!-- ENDS FOOTER -->

	
	</body>
</html>