<!-- TABS -->
					<!-- the tabs -->
					<ul class="tabs">
						<li><a href="#"><?=  Application_Service_Translate::_('taxi_titles_1')?></a></li>
						<li><a href="#"><?=  Application_Service_Translate::_('taxi_titles_2')?></a></li>
						<li><a href="#"><?=  Application_Service_Translate::_('taxi_titles_3')?></a></li>
						<li><a href="#"><?=  Application_Service_Translate::_('taxi_titles_4')?></a></li>
						
				  </ul>
					
					<!-- tab "panes" -->
					<div class="panes">
					
						<!-- Information  -->
						<div>

	
</div>
<!-- ENDS Information -->

<!-- Post list -->
<div>
      
</div>
<!-- ENDS Post list -->


<!-- img gallery -->
<div>
    
</div>
<!-- ENDS img gallery -->

<!-- img gallery -->
<div>

</div>
<!-- ENDS img gallery -->

</div>
<!-- ENDS TABS -->


