<div class="round-box-border css3">

                        
    <table>
    <tr>
        <td style="border: none;"><img width="200" height="200" src="/img/logoForContest.png" alt="Elogra" id="logo" /></td>
        <td style="border: none;"><h1>و</h1></td>
        <td style="border: none;"><img width="250" height="250" src="/img/teenstuff.jpg" alt="Elogra" id="logo" /></td>
    </tr>
</table>
    
<div align="center"> <h1>عاملين مسابقة</h1>
    <br></div>
        		إدخل على الأجرة وشير حدوتك معانا وأحسن عشر حواديت الناس حاتختارهم كل شهر حاننشرهم في مجلة  

                        <b>TeenStuff</b>
                        
                        <br></br>
                        <br></br>
</div>
