<table border="1">

	<tr>
	<td>
	<?=  Application_Service_Translate::_('live_fare')?>
	</td>
	<td>
	<?=$this->searchResults->liveFare?>
	</td>
	<td>
	<?=  Application_Service_Translate::_('history_fare')?>
	</td>
	<td>
	<?=$this->searchResults->historyFare?>
	</td>
	</tr>
</table>
<div class="paginated" data-page="1" data-from="<?=$this->from?>" data-to="<?=$this->to?>" data-taxi="<?=$this->taxi?>">
    
        <?php
    foreach ($this->searchResults->comments as $comment) {
?>
        <?=$this->partial('partials/_entrySearch.phtml',array('comment'=>$comment));?>
    <?php
	}
?>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        
        $(window).scroll(function(){
            if  ($(window).scrollTop() == $(document).height() - $(window).height()){//only when scrolling down
                       getMore(); 
            }
        });
                
        function getMore(){
            $.ajax({
                url: "<?= $this->url(array('controller' => 'search', 'action' => 'more'), 'default', true) ?>",
                dataType: "json", 
                data: getPaginationData(),
                beforeSend:function(){ // Are not working with dataType:'jsonp'
                    $('.paginated').after("<div align='center'><img  id='loading' src='/img/progressbar.gif' /></div>");
                },
                complete: function(){
                    $('#loading').remove();
                },
                success: function(data) {
                    $(".paginated").append(data.html);
                    var page = $(".paginated").attr('data-page');
                    page++;
                    $(".paginated").attr('data-page',page);
                }
             });
        }
         
         function getPaginationData(){
            var page = $(".paginated").attr('data-page');
            page++;
            var from = $(".paginated").attr('data-from');
            var to = $(".paginated").attr('data-to');
            var taxi = $(".paginated").attr('data-taxi');
            return {page: page, from :from, to: to, taxi: taxi};
         }
         
         
        
        
    });
</script>