<table border="1">

	<tr>
	<td>
	Live Fare
	</td>
	<td>
	<?=$this->searchResults->liveFare?>
	</td>
	<td>
	History Fare
	</td>
	<td>
	<?=$this->searchResults->historyFare?>
	</td>
	</tr>
</table>
<div class="paginated" data-page="1" data-from="<?=$this->from?>" data-to="<?=$this->to?>" data-taxi="<?=$this->taxi?>">
    <?=$this->partial('partials/_entrySearch.phtml',array('comments'=>$this->searchResults->comments));?>
</div>
<button id="more">More</button>

<script type="text/javascript">
    $(document).ready(function(){
        
        $("#more").click(function(){
            getMore(); 
        });
        
        function getMore(){
            $.ajax({
                url: "<?= $this->url(array('controller' => 'search', 'action' => 'more'), 'default', true) ?>",
                dataType: "json", 
                data: getPaginationData(),
                success: function(data) {
                    $("")
                }
             });
        }
         
         function getPaginationData(){
            var page = $(".paginated").attr('data-page');
            page++;
            var from = $(".paginated").attr('data-from');
            var to = $(".paginated").attr('data-to');
            var taxi = $(".paginated").attr('data-taxi');
            return {page: page, from :from, to: to, taxi: taxi};
         }
         
         
        
        
    });
</script>