<div id="alert-area"></div>
<div>
		<form id="form1" name="form1" method="post" action="<?=$this->url(array('controller'=>'search','action'=>'get'),'default',true)?>"
			class="well">
			<fieldset>
				<label><?=  Application_Service_Translate::_('from')?>
				</label> <select size="1.1" name="from" id="from">
					<option value=0><?=  Application_Service_Translate::_('choose')?></option>
				</select> <select size="1.1" name="fromHS" id="fromHS">
					<option value=0><?=  Application_Service_Translate::_('choose')?></option>
				</select> <label><?=  Application_Service_Translate::_('to')?>
				</label> <select size="1.1" name="to" id="to">
					<option value=0><?=  Application_Service_Translate::_('choose')?></option>
				</select> <select size="1.1" name="toHS" id="toHS">
					<option value=0><?=  Application_Service_Translate::_('choose')?></option>
				</select>
				<div class="control-group">
					<label class="control-label">
                                            <?=  Application_Service_Translate::_('taxi_type')?> 
                                        </label>

					<div class="controls">
						<img class="imgRadio" src="/img/blackTaxis.jpg" data-value="1" />
						<img class="imgRadio" src="/img/whiteTaxis.jpg" data-value="2" />
						<img class="imgRadio" src="/img/yellowTaxis.jpg" data-value="3" />
						<img class="imgRadio" src="/img/londonTaxis.jpg" data-value="4" />
						<input type="hidden" id="imgRadio-input" name="imgRadio-input" />
					</div>
				</div>
				<input type="submit" name="button" id="button"
					value="<?=  Application_Service_Translate::_('search')?>"
					class="btn btn-large" />
			</fieldset>
		</form>
<script type="text/javascript">
 $(document).ready(function(){
  	
    loadCascadingCombo("from","fromHS");
    loadCascadingCombo("to","toHS");
    
    function loadCascadingCombo(parentId,childId){
        $.ajax({
            url: "<?=$this->url(array('controller'=>'ajax','action'=>'gettoplevelareas'),'default',true)?>",
            cache: false,
            dataType: "json",
            success: function(data){
                $.each(data, function(i, item) {
                    $("#"+parentId).append($('<option/>').val(data[i].id).text(data[i].name));
                });
			  
            },
            error: function(e, xhr){
                console.log("ajax error");
            }
        });
  		  		
	$("#"+parentId).change(function(){
                $.ajax({
                    url: "<?=$this->url(array('controller'=>'ajax','action'=>'getareasunder'),'default',true)?>",
                    dataType: "json", 
                    data: {id : $(this).val()},
                    success: function(data) {
                        $("#"+childId).empty();
                        $.each(data, function(i, item) {
                            $("#"+childId).append($('<option/>').val(data[i].id).text(data[i].name));
                        });
                        $("#"+childId).trigger("change");
                    }});


        });
    }
    $('#form1').submit(function() {
        if($("#from").val() == 0){
            $("#alert-area").append($("<div id=\"error-alert\" class=\"alert alert-error\"><a class=\"close\" data-dismiss=\"alert\">×</a> <strong>أختار منين</strong></div> "));
            $("#error-alert").delay(2000).fadeOut("slow", function () { $(this).remove(); });
            return false;
        }else if($("#fromHS").val() == 0){
            $("#alert-area").append($("<div id=\"error-alert\" class=\"alert alert-error\"><a class=\"close\" data-dismiss=\"alert\">×</a> <strong>أختار منين</strong></div> "));
            $("#error-alert").delay(2000).fadeOut("slow", function () { $(this).remove(); });
            return false;
        }else if($("#to").val() == 0){
            $("#alert-area").append($("<div id=\"error-alert\" class=\"alert alert-error\"><a class=\"close\" data-dismiss=\"alert\">×</a> <strong>أختار لفين</strong></div> "));
            $("#error-alert").delay(2000).fadeOut("slow", function () { $(this).remove(); });
            return false;
        }else if($("#toHS").val() == 0){
            $("#alert-area").append($("<div id=\"error-alert\" class=\"alert alert-error\"><a class=\"close\" data-dismiss=\"alert\">×</a> <strong>أختار لفين</strong></div> "));
            $("#error-alert").delay(2000).fadeOut("slow", function () { $(this).remove(); });
            return false;
        }else if($("#imgRadio-input").val() == ''){
            $("#alert-area").append($("<div id=\"error-alert\" class=\"alert alert-error\"><a class=\"close\" data-dismiss=\"alert\">×</a> <strong>أختار لون التاكسى</strong></div> "));
            $("#error-alert").delay(2000).fadeOut("slow", function () { $(this).remove(); });
            return false;
        }else if($("#toHS").val() == $("#fromHS").val()){
            $("#alert-area").append($("<div id=\"error-alert\" class=\"alert alert-error\"><a class=\"close\" data-dismiss=\"alert\">×</a> <strong>مينفعش تختار نفس المنطقة</strong></div> "));
            $("#error-alert").delay(2000).fadeOut("slow", function () { $(this).remove(); });
            return false;
        }
    });	

	
});

</script>

</div>